main:
  push: &testing
    - name: testing
      lock:
        key: testing-$CNB_BRANCH
        cancel-in-progress: true
      docker:
        image: golang:1.25
      services:
        - docker
      stages:
        - name: start dependencies
          script: |
            docker run -d --name redis -p 6379:6379 ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/redis:7-alpine

            for i in $(seq 1 30); do
              if docker exec redis redis-cli ping | grep -q PONG; then
                exit 0
              fi
              sleep 1
            done

            docker logs redis
            exit 1

        - name: test
          env:
            DATABASE_REDIS: redis://127.0.0.1:6379
          script: |
            go mod tidy
            go test -race -covermode atomic -coverprofile=covprofile ./...

        - name: report coverage
          type: testing:coverage
          options:
            pattern: covprofile
            lang: go

        - name: sync to github
          if: '[ "$CNB_EVENT" = "push" ]'
          imports: https://cnb.cool/kainonly/secrets/-/blob/main/github.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/kainonly/go.git
            auth_type: https
            username: $GIT_USERNAME
            password: $GIT_PASSWORD
            push_tags: true
            force: true

  pull_request: *testing

$:
  tag_push:
    - name: release
      docker:
        image: golang:1.25
      stages:
        - name: test
          script: go test ./...

        - name: sync to github
          imports: https://cnb.cool/kainonly/secrets/-/blob/main/github.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/kainonly/go.git
            auth_type: https
            username: $GIT_USERNAME
            password: $GIT_PASSWORD
            push_tags: true
            force: true

        - name: release
          type: git:release

        - name: update go module proxy index
          script: curl -f "https://goproxy.cn/github.com/kainonly/go/@v/$CNB_BRANCH.info" || true
